# Deploy to Firebase Hosting when merged to main
name: Deploy Flutter Web to Firebase Hosting (Live)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2' # match your local flutter --version output
          channel: 'stable'

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build web app
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTITUTION_PAYMENT_SYSTEM }}
          channelId: live
          projectId: institution-payment-system
