name: Build & Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug list files (repo root)
        run: |
          pwd
          ls -la

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Build Flutter Web (release)
        run: |
          flutter pub get
          flutter build web --release

      # This action reads firebase.json from the path given by entryPoint.
      # Since your firebase.json is at the repo root, entryPoint should be "./".
      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTITUTION_PAYMENT_SYSTEM }}
          projectId: institution-payment-system
          channelId: live
          entryPoint: ./   # <-- IMPORTANT: points to where firebase.json lives (repo root)
